name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://spl.vighnesh153.com --delete --cache-control 'public, max-age=300, s-maxage=31536000'

      - name: Cloudfront invalidate
        run: aws cloudfront create-invalidation --paths '/*' --distribution-id E3LW557NYJ7YVU
